#%RAML 1.0 NamedExample

value:
  FirstName: Jonathan
  LastName: Smith,
  StreetAddress1: 27 W. 24th St.
  StreetAddress2: Suite 404
  City: New York
  State: NY
  Zip: '10010'
  DOB: '2000-01-30'
  SSN: '000110001'
  Phone: '3126227000'
  Email: jsmith@example.com
  Branch: '107'
  ProdCode: '044'
  BinNumber:  '004356'
  DPExcpPlnNbr: 100
  Occupation: Account Manager
  OccupationStatus: employed
  Citizenship: US
  MothersMaiden: Bellinger
  IDType: 002
  IDNumber: '1234567890'
  IDIssued: '2017-01-2'
  IDExpired: '2021-01-30'
  IDState: 'CA'
  SrcOfFunds: 'loan'
  TypOfFunds: 'check'
  PrpOfAcct: 'deposit'
  NbrOfDp: '0'
  TotDpAmt: '0'
  NbrOfCashDp: '0'
  CashDpAmt: '0'
  NbrOfCashWthdrwl: '0'
  CashWthdrwlAmt: '0'
  AntWireAct: '0'
  DomInWireAct: '0'
  NbrDomWire: '0'
  DomInWireAmt: '0'
  DomOutWireAct: '0'
  NbrDomOutWire: '0'
  DomOutWireAmt: '0'
  FrgnInWireAct: '0'
  InCtryCde: '0'
  NbrFrgnInWire: '0'
  FrgnInWireAmt: '0'
  FrgnOutWireAct: '0'
  NbrFrgnOutWire: '0'
  FrgnOutWireAmt: '0'
  OutCtryCde: '0'